{% set name = "pydyf" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 394dddf619cca9d0c55715e3c55ea121a9bf9cbc780cdc1201a2427917b86b64

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pydyf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.courtbouillon.org/pydyf
  summary: A low-level PDF generator.
  license: BSD-3-Clause
  license_file:
    - LICENSE
  dev_url: https://github.com/CourtBouillon/pydyf
  doc_url: https://doc.courtbouillon.org/pydyf/

extra:
  recipe-maintainers:
    - liZe
    - BastianZim
